workflows:
  build_apk:
    name: Build Flutter APK
    max_build_duration: 60
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - raushan7171@gmail.com
